import os ,sys 

from src.constant import * 


ROOT_DIR = ROOT_DIRECTORY 
INITIAL_DATASET_PATH = os.path.join(ROOT_DIR ,INITIAL_DATA_DIR ,INITIAL_DATA_DATASET)


RAW_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_INGESTION_DIR ,CURRENT_TIME_STAMP ,DATA_INGESTION_RAW_DATA_DIR ,DATA_INGESTION_RAW_DATA_DATASET)

RAW_TRAIN_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_INGESTION_DIR ,CURRENT_TIME_STAMP ,DATA_INGESTION_INGESTED_DATA_DIR ,DATA_INGESTION_INGESTED_DATA_TRAIN_DATASET)
RAW_TEST_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_INGESTION_DIR ,CURRENT_TIME_STAMP ,DATA_INGESTION_INGESTED_DATA_DIR ,DATA_INGESTION_INGESTED_DATA_TEST_DATASET)

PREPROCESSOR_OBJ_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_TRANSFORMATION_DIR ,DATA_TRANSFORMATION_PROCESSOR_DIR ,DATA_TRANSFORMATION_PREPROCESSOR_OBJ)
FEATURE_ENFINEERING_OBJ_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_TRANSFORMATION_DIR ,DATA_TRANSFORMATION_PROCESSOR_DIR ,DATA_TRANSFORMATION_FEATURE_ENGINEERING_OBJ)

TRANSFORMED_TRAIN_FILE_PATH=os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_TRANSFORMATION_DIR ,DATA_TRANSFORMATION_TRANSFORMER_DIR ,DATA_TRANSFORMATION_TRANSFORMER_TRAIN_DATASET)
TRANSFORMED_TEST_FILE_PATH =os.path.join(ROOT_DIR ,ARTIFACT_DIR ,DATA_TRANSFORMATION_DIR ,DATA_TRANSFORMATION_TRANSFORMER_DIR ,DATA_TRANSFORMATION_TRANSFORMER_TEST_DATASET)

MODEL_TRAINER_FILE_PATH = os.path.join(ROOT_DIR ,ARTIFACT_DIR ,MODEL_TRAINER_DIR ,MODEL_TRAINER_OBJ)